use = true
table_name = "mrt_shop__counters"
schema_name = "marts"
event_time = "period"

[[columns]]
name = "Код магазина"
alias = "wh_single_code"
type = "string"

[[columns]]
name = "Период, день"
alias = "period"
type = "date"

[[columns]]
name = "ГУИДМагазина"
alias = "wh_guid"
type = "uuid"

[[columns]]
name = "Количество посетителей"
alias = "count_customers"
type = "int"

[[columns]]
name = "Количество чеков (по продавцам)"
alias = "count_cheques"
type = "int"

[[indexes]]
use = false
name = "default_idx"
columns = ["Период, день", "Код магазина"]
unique = false