use = true
table_name = "int_rep__arenda_festival"
schema_name = "intermediate"
event_time = "period_month"
comment = ""

[[columns]]
name = "Месяц"
alias = "period_month"
type = "date"
comment = "Период месяц"

[[columns]]
name = "Сумма"
alias = "cost_amount"
type = "int"
comment = "Сумма"

[[columns]]
name = "Подразделение"
alias = "wh_name"
type = "string"
comment = "Подразделение"

[[columns]]
name = "ЕдиныйКод"
alias = "wh_single_code"
type = "string"
comment = "Эдин код"

[[columns]]
name = "Статья"
alias = "cost_item"
type = "string"
comment = "Статья затрат"

[[indexes]]
use = true
name = "arenda_unique_idx"
columns = ["period_month", "wh_single_code", "cost_item"]
unique = true
