use = false
table_name = "лдАнализПродажПродавцов_PBI (TXT)_table"
schema_name = "marts"
event_time = ""
comment = ""

[[columns]]
name = "Код магазина"
alias = "код_магазина"
type = "string"
comment = ""

[[columns]]
name = "Период, день"
alias = "период,_день"
type = "string"
comment = ""

[[columns]]
name = "ГУИДМагазина"
alias = "гуидмагазина"
type = "string"
comment = ""

[[columns]]
name = "Количество посетителей"
alias = "количество_посетителей"
type = "string"
comment = ""

[[columns]]
name = "Количество чеков (по продавцам)"
alias = "количество_чеков_(по_продавцам)"
type = "string"
comment = ""

[[indexes]]
use = false
name = "default_idx"
columns = ["код_магазина"]
unique = false
