use = true
table_name = "rep_invoice__yamarket"
schema_name = "marts"
event_time = "date"
comment = "Состояние Заказа. Отчет УТ11: ЭффективностьМультискладаЯМПодВыгрузку"

[[columns]]
name = "date"
alias = "date"
type = "date"
comment = "Дата Заказа"

[[columns]]
name = "mp_agreement"
alias = "mp_agreement"
type = "string"
comment = "Вид доставки"

[[columns]]
name = "Mp agreement type"
alias = "mp_agreement_type"
type = "string"
comment = "Вид доставки.Типы отношений с маркетплейсом (лд)"

[[columns]]
name = "Client order"
alias = "client_order"
type = "string"
comment = "Заказ клиента"

[[columns]]
name = "Client order date"
alias = "client_order_date"
type = "date"
comment = "Заказ клиента.Дата"

[[columns]]
name = "item_guid"
alias = "item_guid"
type = "uuid"
comment = "UUID Номенклатуры"

[[columns]]
name = "item_name"
alias = "item_name"
type = "string"
comment = "Номенклатура"

[[columns]]
name = "Wh single code"
alias = "wh_single_code"
type = "string"
comment = "Склад.Един код (Склады и магазины)"

[[columns]]
name = "wh_name"
alias = "wh_name"
type = "int"
comment = "Склад"

[[columns]]
name = "Order"
alias = "order"
type = "int"
comment = "Заказ клиента"

#---Заказано-------------------------------------------------------------------------
[[columns]]
name = "ordered_orders"
alias = "ordered_orders"
type = "int"
comment = "Заказано: Количество заказов"

[[columns]]
name = "ordered_items"
alias = "ordered_items"
type = "int"
comment = "Заказано: Количество номенклатуры"

[[columns]]
name = "ordered_sum"
alias = "ordered_sum"
type = "int"
comment = "Заказано: Стоимость"

#---В обработке----------------------------------------------------------------------
[[columns]]
name = "in_processing_orders"
alias = "in_processing_orders"
type = "int"
comment = "В обработке: Количество заказов"

[[columns]]
name = "in_processing_items"
alias = "in_processing_items"
type = "int"
comment = "В обработке:  Количество номенклатуры"

[[columns]]
name = "in_processing_sum"
alias = "in_processing_sum"
type = "int"
comment = "В обработке: Сумма"

[[columns]]
name = "ready_orders"
alias = "ready_orders"
type = "int"
comment = "В обработке: Количество заказов готовое к выдаче"

[[columns]]
name = "ready_items"
alias = "ready_items"
type = "int"
comment = "В обработке: Количество товаров готовое к выдаче"

[[columns]]
name = "ready_sum"
alias = "ready_sum"
type = "int"
comment = "В обработке: Сумма товаров готовое к выдаче"

# ---Отменено------------------------------------------------------------------------
[[columns]]
name = "cancelled_orders"
alias = "cancelled_orders"
type = "int"
comment = "Отменено: Количество заказов"

[[columns]]
name = "cancelled_items"
alias = "cancelled_items"
type = "int"
comment = "Отменено: Количество номенклатуры"

[[columns]]
name = "cancelled_sum"
alias = "cancelled_sum"
type = "int"
comment = "Отменено: Стоимость"

[[columns]]
name = "cancel_by_client_items"
alias = "cancel_by_client_items"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) по просьбе клиента - товары"

[[columns]]
name = "cancel_by_client_sum"
alias = "cancel_by_client_sum"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) по просьбе клиента - стоимость"

[[columns]]
name = "cancel_out_of_stock_items"
alias = "cancel_out_of_stock_items"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) Нет в наличии - товары"

[[columns]]
name = "cancel_out_of_stock_sum"
alias = "cancel_out_of_stock_sum"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) Нет в наличии - стоимость"

[[columns]]
name = "cancel_expired_items"
alias = "cancel_expired_items"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) Нет в наличии - истек срок хранения товара"

[[columns]]
name = "cancel_expired_sum"
alias = "cancel_expired_sum"
type = "int"
comment = "Отменено: (Причины отмен взятых в работу товаров) Нет в наличии - истек срок хранения - Стоимость"

# ---В пути--------------------------------------------------------------------------
[[columns]]
name = "on_way_orders"
alias = "on_way_orders"
type = "int"
comment = "В пути: Количество заказов"

[[columns]]
name = "on_way_items"
alias = "on_way_items"
type = "int"
comment = "В пути: Товары"

[[columns]]
name = "on_way_sum"
alias = "on_way_sum"
type = "int"
comment = "В пути: Стоимость"

# ---Выкуплено-----------------------------------------------------------------------
[[columns]]
name = "sold_orders"
alias = "sold_orders"
type = "int"
comment = "Выкуплено: Количестао заказов"

[[columns]]
name = "sold_items"
alias = "sold_items"
type = "int"
comment = "Выкуплено: Количество"

[[columns]]
name = "sold_sum"
alias = "sold_sum"
type = "int"
comment = "Выкуплено: Стоимость"

[[columns]]
name = "sold_cost"
alias = "sold_cost"
type = "int"
comment = "Выкуплено: Себестоимость товаров выкуплено"

[[columns]]
name = "sold_full_price"
alias = "sold_full_price"
type = "int"
comment = "Выкуплено: Сумма товаров выкуплено без скидок"

# ---Не выкуплено--------------------------------------------------------------------
[[columns]]
name = "not_sold_orders"
alias = "not_sold_orders"
type = "int"
comment = "Не выкуплено: Количество заказов"

[[columns]]
name = "not_sold_items"
alias = "not_sold_items"
type = "int"
comment = "Не выкуплено: Количество"

[[columns]]
name = "not_sold_sum"
alias = "not_sold_sum"
type = "int"
comment = "Не выкуплено: Стоимость"

# ---Себестоимость товаров возвраты--------------------------------------------------
[[columns]]
name = "returned_items"
alias = "returned_items"
type = "int"
comment = "Возвращено после выкупа: Количество"

[[columns]]
name = "returned_sum"
alias = "returned_sum"
type = "int"
comment = "Возвращено после выкупа: Стоимость"

[[columns]]
name = "returned_cost"
alias = "returned_cost"
type = "int"
comment = "Возвращено после выкупа: Себестоимость товаров возвраты"

# ---ИТОГ----------------------------------------------------------------------------
[[columns]]
name = "total_sum"
alias = "total_sum"
type = "int"
comment = "ИТОГ: Сумма"

[[columns]]
name = "total_cost"
alias = "total_cost"
type = "int"
comment = "ИТОГ: Себестоимость"

#---Индекс---------------------------------------------------------------------------
[[indexes]]
use = false
name = "default_idx"
columns = ["date"]
unique = false
