[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)"]
use = false
table_name = "лдАнализПродажПродавцов_PBI (TXT)_table"
schema_name = "marts"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".columns]]
name = "КодМагазина"
alias = "кодмагазина"
type = "string"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".columns]]
name = "Период,День"
alias = "период,день"
type = "string"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".columns]]
name = "Гуидмагазина"
alias = "гуидмагазина"
type = "string"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".columns]]
name = "КоличествоПосетителей"
alias = "количествопосетителей"
type = "string"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".columns]]
name = "КоличествоЧеков(ПоПродавцам)"
alias = "количествочеков(попродавцам)"
type = "string"

[[reports_export_settings."лдАнализПродажПродавцов_PBI (TXT)".indexes]]
use = false
name = "default_idx"
columns = ["КодМагазина"]
unique = false
